---
dotfiles_repo: https://github.com/jlauding/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Provision/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - chromedriver
  - doxygen
  - gettext
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libdvdcss
  - libevent
  - packer
  - python
  - sqlite
  - mcrypt
  - mysql
  - nmap
  - npm
  - nvm
  - php70
  - php70-mcrypt
  - php70-xdebug
  - ssh-copy-id
  - cowsay
  - readline
  - subversion
  - openssl
  - pv
  - drush
  - wget
  - wrk

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/php
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - dropbox
  - firefox
  - google-chrome
  - java
  - kdiff3
  - macvim
  - sequel-pro
  - skype
  - slack
  - sublime-text
  - transmit
  - vagrant
  - virtualbox
  - vlc
  - tunnelblick
  - 1password
  - alfred
  - spectacle
  - spotify
  - iterm2
  - fantastical
  - sketch
  - google-drive
  - caffeine
  - evernote

# See `geerlingguy.mas` role documentation for usage instructions.
mas_email: ""
mas_password: ""
mas_installed_app_ids:
  - 952087822 # Ruler Tool (4.1.0)
  - 992076693 # MindNode (2.4.5)
  - 410628904 # Wunderlist (3.4.6)
  - 435989461 # GIFBrewery (2.3.5)
  - 1176895641 # Spark (1.1.0)
  - 481981128 # Gradient (1.1)
  - 1054607607 # Helium (2.0)
